### ISSUE TITLE
Добавления/улучшения

### ISSUE THREAD

**Issue by xXnekit101Xx** [RSTeamCore/WorldGuardRegionProtect#113]
### What feature do you want to see added?

Добавьте защиту от инструмента SuperPickaxe, от плагина WorldEdit, а то если регион защищён, то игрок всё равно может ломать регион киркой, на которой изменён радиус разрушения. 

### Anything else?

Также хотелось бы видеть, чтобы в списках флагах региона, был флаг protect true/false (Для обычных игроков, для их построек.)
А флаг adminprotect: true/false (Для администрации, на защиту спавна либо чего-то ещё)
И чтобы была ещё команда /protect add - для защиты своих построек. (Для обычных игроков).

**Comment by RitaSister** [comment]
большая часть функций была уже реализована.
