### ISSUE TITLE
ПРИОРИТЕТЫ НАШЕ ВСЁ

### ISSUE THREAD

**Issue by moda84** [RSTeamCore/WorldGuardRegionProtect#76]
### What feature do you want to see added?

Если регион с высшим приоритетом не под защитой, но находится в/имеет общую зону с регионом, который под защитой, то защита не будет действовать на зону региона высшего приоритета

### Are there any alternatives?

Учёт приоритета регионов

**Comment by RitaSister** [comment]
api соотвествующее было добавлено, но реализация ещё не была добавлена до конца, скоро спустя два года будет)
