### ISSUE TITLE
Проблема с пропиской команды, которые указаны в конфиге 

### ISSUE THREAD

**Issue by TheFaik** [RSTeamCore/WorldGuardRegionProtect#77]
### Server Implementation

Spigot

### Server Version

1.19.3

### Describe the bug

Здравствуйте! Я использую ваш плагин, а именно 0.6.1 и проблема состоит в том, что команды, которые в писаны в плагин работают потом с ошибкой. К примеру я хочу по приколу написать команду //set, но выделять я ничего не хочу(это ключевое) и в итоге, ответа от этой команды нет(сообщения нету в чате, просто пусто), а в консоли вот такая ошибка:
![изображение](https://user-images.githubusercontent.com/99492973/210387973-11afb738-a87b-401e-afaf-9355d0bfcefb.png)
Версия: Purpur - 1.16.5_1171 Проверял я эту ошибку на версии Java: 16.0.1, 17, 18, 19 и одна и та-же ошибка, прошу вас сделать патч на старые версии, ведь больше половины серверов в русском сообществе ещё не могут перейти на более новые версия, а именно выше 1.16.5 Прошу вас сделать с этим, что-нибудь. 
Мои друзья тоже не могут нормально настроить свои сервера из-за таких ошибок, мы все просим сделать обнову на не поддерживаемую версию. УМОЛЯЕМ!!!

### Steps to reproduce

1. Зайти на регион, который под защитой 
2. Прописать любую команду, которая есть в конфиге
3. Вот и ошибка в консоле

### Expected behaviour

Чтобы не было таких фатальных ошибок, а просто-бы написало, что данная команда отключена в этом регионе

### Error log (if applicable)

мы торопимся, пока предоставить логи нету возможности, извенити(

### WorldGuardRegionProtect version

ServerRegionProtect 0.6.1

### Checklist

- [X] I am using the newest build from https://ci.codemc.io/job/RitaSister/job/WorldGuardRegionProtect/ and the issue still persists.

**Comment by RitaSister** [comment]
Эта ошибка давно известна и была исправлена в новых версиях. Так как имеются проблемы с проверками предметов из-за разницы в версий, то это доставляет проблемы для поддержания немного ниже версий. Именно для 1.16.5 требуется?

**Comment by TheFaik** [comment]
да

**Comment by TheFaik** [comment]
Короче используйте версию 0.4.7, и проблемы не будет. Вот ссылка: https://dev.bukkit.org/projects/worldguardregionprotect/files/3253578
