### ISSUE TITLE
Дюп

### ISSUE THREAD

**Issue by Darmoed228** [RSTeamCore/WorldGuardRegionProtect#83]
### What feature do you want to see added?

 Предметы, на которых наложено зачарование soulbound из плагина Enchants Squared, дюпаются. Если умереть с этим зачарованием в регионе защищённом Вашим плагином. У меня на сервере игроки просто прописывали команду /suicide на спавне и дюпали инструменты и броню.

### Anything else?

Оно ещё обрабатывается ютубом и качаство местами будет не очень.Вот посмотрите:    [Видео](https://youtu.be/WSyd_1mWEOI)

**Comment by RitaSister** [comment]
Вы неправильно создали запрос. Просьба создать заново запрос по шаблону "баги".
