### ISSUE TITLE
Ошибка в консоли

### ISSUE THREAD

**Issue by TheFaik** [RSTeamCore/WorldGuardRegionProtect#87]
### Server Implementation

Purpur

### Server Version

1.20

### Describe the bug

Ставлю кристалл Энда на регионе под защитой WGRP, бью по кристаллу он взрывается и после ошибка в консоли 

### Steps to reproduce

1. Ставим кристалл на регионе под защитой WGRP.
2. Ударяем по кристаллу 
3. Кристалл ломается и плюс ошибка в консоли

### Expected behaviour

.

### Error log (if applicable)

https://pastebin.com/mqNPGfKt

### WorldGuardRegionProtect version

v0.9.4

### Checklist

- [X] I am using the newest build from https://ci.codemc.io/job/rsteamcore/job/WorldGuardRegionProtect/ and the issue still persists.

**Comment by RitaSister** [comment]
you don't provide full log of server.
