### ISSUE TITLE
Ошибка при выключении сервера

### ISSUE THREAD

**Issue by BestMark** [RSTeamCore/WorldGuardRegionProtect#88]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

https://pastebin.com/Xqy79R2z

### Steps to reproduce

1. Установить плагин (не настраивать)
2. Написать команду "stop" в консоли

### Expected behaviour

Появится краш в логе: https://pastebin.com/Xqy79R2z

### Error log (if applicable)

https://pastebin.com/Xqy79R2z

### WorldGuardRegionProtect version

0.9.4

### Checklist

- [X] I am using the newest build from https://ci.codemc.io/job/rsteamcore/job/WorldGuardRegionProtect/ and the issue still persists.

**Comment by RitaSister** [comment]
please prodive full log of your server.
